version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb

  horsefy-api:
    image: georgkivivali1/horsefy-api
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8080:8080"

  horsefy-frontend:
    build: ./src/frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on: [ "horsefy-api" ]
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=localhost
      - HOST_API=localhost:8080

volumes:
    data: {
    }
